/**
 * Approved GSDC WBS structure for Cost → Budget template seeding.
 * Source: GSDC-WBS-R1 (20.02.2026), sheet "WBS".
 * Parents are derived from code hierarchy (last segment removed).
 */
export const APPROVED_COST_WBS_TEMPLATE = [
  { code: "00", description: "GSDC Internal  Land Purchase Costs" },
  { code: "01", description: "Land Purchase" },
  { code: "09", description: "Contingency" },
  { code: "09.01", description: "Land Purcahse Contingency" },
  { code: "10", description: "GSDC Development" },
  { code: "10.01", description: "GSDC Development Costs" },
  { code: "11", description: "Asset Holding Costs" },
  { code: "11.01", description: "Site Ownership / Holding Costs" },
  { code: "11.01.01", description: "Land Tax and Council Rates" },
  { code: "11.01.02", description: "Strata Levies / Body Corporate Fees" },
  { code: "11.01.03", description: "Ground Rent or Lease Payments" },
  { code: "11.01.04", description: "Service Charges" },
  { code: "11.01.05", description: "Water Access & Sewer Charges" },
  { code: "11.01.06", description: "Environmental Levies / Authority Charges" },
  { code: "11.01.07", description: "Legal and Advisory Fees" },
  { code: "11.02", description: "Insurance" },
  { code: "11.02.01", description: "Building and Asset Insurance" },
  { code: "11.02.02", description: "Public Liability and Third-Party Cover" },
  { code: "11.02.03", description: "Risk Premium Adjustments / Brokerage Fees" },
  { code: "11.03", description: "Maintenance (Interim)" },
  { code: "11.03.01", description: "Grounds and Landscaping Maintenance" },
  { code: "11.03.02", description: "Fire Safety & Essential Services Testing" },
  { code: "11.03.03", description: "HVAC, Lifts & Mechanical Servicing" },
  { code: "11.03.04", description: "Building Fabric and Minor Repairs" },
  { code: "11.03.05", description: "Cleaning, Pest Control & Waste Management" },
  { code: "11.03.06", description: "FM – Plant Room, System Inspections, Reactive Maintenance" },
  { code: "11.04", description: "Utilities & Services" },
  { code: "11.04.01", description: "Electricity Supply / Network Access Charges" },
  { code: "11.04.02", description: "Water and Sewer Usage / Connection Fees" },
  { code: "11.04.03", description: "Telecoms and Data Services" },
  { code: "11.04.04", description: "Waste Disposal and Recycling" },
  { code: "11.04.05", description: "Utility Standing Charges & Meter Readings" },
  { code: "11.05", description: "Security & Access Control" },
  { code: "11.05.01", description: "Static Guards / Patrols" },
  { code: "11.05.02", description: "CCTV Monitoring & Maintenance" },
  { code: "11.05.03", description: "Access Cards, Keys and Control Systems" },
  { code: "11.05.04", description: "Temporary Fencing / Perimeter Controls" },
  { code: "11.06", description: "Statutory Fees & Compliance" },
  { code: "11.06.01", description: "Fire Safety Certification Renewals" },
  { code: "11.06.02", description: "Building Code / Occupancy Compliance Audits" },
  { code: "11.06.03", description: "Environmental or Heritage Permits / Renewals" },
  { code: "11.06.04", description: "Workplace Health and Safety Audits" },
  { code: "12", description: "Due Diligence" },
  { code: "12.01", description: "Land Purchase" },
  { code: "12.01.01", description: "Valuation" },
  { code: "12.01.02", description: "Legal Fees" },
  { code: "12.01.03", description: "FiRB" },
  { code: "12.02", description: "Planning & Legal" },
  { code: "12.02.01", description: "Town Planner" },
  { code: "12.02.02", description: "Legal Fees" },
  { code: "12.02.03", description: "Utility Application Fees / Inquiry Fees" },
  { code: "12.03", description: "Design & Technical Advisory" },
  { code: "12.03.01", description: "Due-Diligence Consultant" },
  { code: "12.03.02", description: "Architect & Landscaping" },
  { code: "12.03.03", description: "Civil" },
  { code: "12.03.04", description: "Structural" },
  { code: "12.03.05", description: "Flood" },
  { code: "12.03.06", description: "Building Services / MEP" },
  { code: "12.03.07", description: "Telecommunications" },
  { code: "12.03.08", description: "Fibre Specialist" },
  { code: "12.03.09", description: "Power Consultant" },
  { code: "12.03.10", description: "Gas, Water & Sewer" },
  { code: "12.03.11", description: "Acoustics" },
  { code: "12.03.12", description: "Design Management Fee / Peer Review" },
  { code: "12.03.13", description: "Constructability" },
  { code: "12.04", description: "Environmental & Site Investigations" },
  { code: "12.04.01", description: "Surveyor" },
  { code: "12.04.02", description: "Geotechnical Engineer" },
  { code: "12.04.03", description: "Environmental Consulting" },
  { code: "12.04.04", description: "Arborist" },
  { code: "12.04.05", description: "Heritage" },
  { code: "12.04.06", description: "ESD / Sustainability Consultant" },
  { code: "12.04.07", description: "Site Investigations / Bore Holes" },
  { code: "12.05", description: "Commercial & Project Controls" },
  { code: "12.05.01", description: "Project Manager" },
  { code: "12.05.02", description: "Cost Manager" },
  { code: "12.06", description: "Specialist Consultants" },
  { code: "12.06.01", description: "ICT / DC Specialists" },
  { code: "12.06.02", description: "Security" },
  { code: "12.06.03", description: "Fire Engineer" },
  { code: "13", description: "Design & Development" },
  { code: "13.01", description: "Design Consultants" },
  { code: "13.01.01", description: "Civil Design" },
  { code: "13.01.02", description: "Structural Design" },
  { code: "13.01.03", description: "Architectural Design" },
  { code: "13.01.04", description: "Façade" },
  { code: "13.01.05", description: "Landscape Architect" },
  { code: "13.01.06", description: "Geotechnical & Contamination" },
  { code: "13.01.07", description: "Surveyor" },
  { code: "13.01.08", description: "Traffic & Transport Engineering" },
  { code: "13.01.09", description: "Town Planning" },
  { code: "13.01.10", description: "Mechanical Engineering" },
  { code: "13.01.11", description: "Computational Fluid Dynamics (CFD)" },
  { code: "13.01.12", description: "Electrical Engineering" },
  { code: "13.01.13", description: "Hydraulic Engineering" },
  { code: "13.01.14", description: "Fire Services Design" },
  { code: "13.01.15", description: "Fire Safety Engineering" },
  { code: "13.01.16", description: "Vertical Transport Design" },
  { code: "13.01.17", description: "Security Design" },
  { code: "13.01.18", description: "Communications, ICT & AV" },
  { code: "13.01.19", description: "Waste Management" },
  { code: "13.01.20", description: "Signage & Wayfinding" },
  { code: "13.01.21", description: "Acoustic & Vibration Engineering" },
  { code: "13.01.22", description: "BCA / PCA & DDA Access Compliance" },
  { code: "13.01.23", description: "ESD / Sustainability Consultant" },
  { code: "13.01.24", description: "Bushfire Consultant" },
  { code: "13.01.25", description: "Arborist" },
  { code: "13.01.26", description: "Heritage Consultant" },
  { code: "13.01.27", description: "Public Relations" },
  { code: "13.01.28", description: "Public Art Consultant" },
  { code: "13.01.29", description: "Hazardous Materials Consultant" },
  { code: "13.01.30", description: "On-Site Substation Design" },
  { code: "13.01.31", description: "Power Utility Design" },
  { code: "13.01.32", description: "Gas Utility Design" },
  { code: "13.01.33", description: "Water Utility Design" },
  { code: "13.01.34", description: "Sewer Utility Design" },
  { code: "13.01.35", description: "Fibre Utility Design" },
  { code: "13.01.36", description: "Uptime Institute Certification Advisor" },
  { code: "13.01.37", description: "BIM Co-ordinator / Digital Engineering" },
  { code: "13.01.38", description: "Document Management System Advisor" },
  { code: "13.01.39", description: "Peer Review / Independent Certifier" },
  { code: "13.01.40", description: "Design Project Management & Markup" },
  { code: "13.02", description: "Development Consultants" },
  { code: "13.02.01", description: "Project Management" },
  { code: "13.02.02", description: "Procurement Management" },
  { code: "13.02.03", description: "Contract Management" },
  { code: "13.02.04", description: "Cost Management" },
  { code: "13.02.05", description: "Programme Management" },
  { code: "13.02.06", description: "Safety Consultant" },
  { code: "13.02.07", description: "Commissioning Agent" },
  { code: "13.02.08", description: "Construction Legal" },
  { code: "13.02.09", description: "Software & Digital Tools" },
  { code: "13.03", description: "Development Costs" },
  { code: "13.03.01", description: "Insurance" },
  { code: "13.03.02", description: "Site Photography" },
  { code: "13.03.03", description: "Financial Audit & Checks" },
  { code: "14", description: "Authority / Planning Costs" },
  { code: "14.01", description: "Authority Application Fees (DA, SSDA, CDC or equivalent)" },
  { code: "14.02", description: "Authority Application Contributions (Statutory S7.11 / S7.12)" },
  { code: "14.03", description: "Authority Application Bonds / Securities" },
  { code: "14.04", description: "Planning Authority Fees & Levies (Council / State)" },
  { code: "14.05", description: "State Design Review Panel (SDRP) Fees" },
  { code: "14.06", description: "Voluntary Planning Agreements (VPAs)" },
  { code: "14.07", description: "Water Utility - Section 73, Feasibility etc." },
  { code: "14.08", description: "Power Utility - Scoping Studies etc." },
  { code: "14.09", description: "Gas Utility – Disconnection etc." },
  { code: "14.10", description: "Fibre Carriers  - Permitting, Applications etc." },
  { code: "14.11", description: "Roads & Transport Authority Requirements" },
  { code: "14.12", description: "Long Service Corporation Levy (Construction Levy)" },
  { code: "14.13", description: "Bushfire, Flood, Acoustic or Site-Specific Studies" },
  { code: "14.14", description: "Contingency Allowance – Authority / Planning" },
  { code: "15", description: "Power & Utilities" },
  { code: "15.01", description: "Offsite HV Utility Cabling" },
  { code: "15.01.01", description: "Design" },
  { code: "15.01.02", description: "Surveys, Locating & Potholing" },
  { code: "15.01.03", description: "Site Establishment" },
  { code: "15.01.04", description: "Project Management" },
  { code: "15.01.05", description: "Civil Works (trenches, pits, conduits)" },
  { code: "15.01.06", description: "HV Cabling Supply (cables, joints, accessories)" },
  { code: "15.01.07", description: "HV Cabling Installation" },
  { code: "15.01.08", description: "Joint Bays Construction" },
  { code: "15.01.09", description: "Underbore / HDD Crossings" },
  { code: "15.01.10", description: "Jointing & Terminations" },
  { code: "15.01.11", description: "Earthing / Grounding" },
  { code: "15.01.12", description: "Testing & Commissioning" },
  { code: "15.01.13", description: "Operating & Maintenance Manuals" },
  { code: "15.02", description: "Substation" },
  { code: "15.02.01", description: "Prelims & General Requirements" },
  { code: "15.02.02", description: "Design & Authority Approvals" },
  { code: "15.02.03", description: "Site Prep & Civil Works" },
  { code: "15.02.04", description: "Roads, Pavements & Access" },
  { code: "15.02.05", description: "Landscaping & Site Finishes" },
  { code: "15.02.06", description: "Site Utilities (water, sewer, comms)" },
  { code: "15.02.07", description: "Substation Earthing System" },
  { code: "15.02.08", description: "Buildings & Structures (switchrooms, enclosures)" },
  { code: "15.02.09", description: "Fencing & External Security Systems" },
  { code: "15.02.10", description: "Incoming Electrical Connections" },
  { code: "15.02.11", description: "MV Substation Feeder Cable Deployment" },
  { code: "15.02.12", description: "LV Substation Feeder Cable Deployment" },
  { code: "15.02.13", description: "Substation Electrical Equipment (transformers, switchgear, protection)" },
  { code: "15.02.14", description: "SCADA, Controls & Communications" },
  { code: "15.02.15", description: "Testing & Commissioning" },
  { code: "15.02.16", description: "Operating & Maintenance Documentation" },
  { code: "15.03", description: "Gas" },
  { code: "15.03.01", description: "Design & Approvals" },
  { code: "15.03.02", description: "Connection Fees (Jemena / APA etc.)" },
  { code: "15.03.03", description: "Headworks Charges – Gas (augmentation, contributions)" },
  { code: "15.03.04", description: "Mains Extension / Diversions" },
  { code: "15.04", description: "Water & Wastewater" },
  { code: "15.04.01", description: "Section 73 Certificate Fees" },
  { code: "15.04.02", description: "Connection Fees" },
  { code: "15.04.03", description: "Headworks Charges – Water & Sewer" },
  { code: "15.04.04", description: "Mains Extension / Diversions" },
  { code: "15.05", description: "Telecommunications / Fibre" },
  { code: "15.05.01", description: "Carrier Design & Approvals (Telstra, NBN, fibre carriers)" },
  { code: "15.05.02", description: "Connection / Build Contributions" },
  { code: "15.05.03", description: "Headworks Charges – Fibre / Carrier Build" },
  { code: "15.05.04", description: "Asset Relocations / Diversions" },
  { code: "15.06", description: "Roads & Transport Authority Requirements" },
  { code: "15.06.01", description: "Road Opening Permits & Fees" },
  { code: "15.06.02", description: "Traffic Management Costs" },
  { code: "15.06.03", description: "Reinstatement Works (pavements, surfaces)" },
  { code: "15.06.04", description: "Authority Inspections & Certifications" },
  { code: "16", description: "Long Lead Equipment" },
  { code: "16.01", description: "Chillers" },
  { code: "16.01.01", description: "Equipment Supply – Air-Cooled Chillers" },
  { code: "16.01.02", description: "Equipment Supply – Water-Cooled Chillers" },
  { code: "16.01.03", description: "Pre-Fabricated Skids" },
  { code: "16.01.04", description: "Delivery & Installation" },
  { code: "16.01.05", description: "Commissioning" },
  { code: "16.01.06", description: "Design, Shop Drawings & Project Management" },
  { code: "16.01.07", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.01.08", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.01.09", description: "Spare Parts" },
  { code: "16.01.10", description: "Maintenance during DLP" },
  { code: "16.02", description: "Cooling Towers & Condensers" },
  { code: "16.02.01", description: "Equipment Supply – Cooling Towers" },
  { code: "16.02.02", description: "Equipment Supply – Condensers" },
  { code: "16.02.03", description: "Pre-Fabricated Skids" },
  { code: "16.02.04", description: "Delivery & Installation" },
  { code: "16.02.05", description: "Commissioning" },
  { code: "16.02.06", description: "Design, Shop Drawings & Project Management" },
  { code: "16.02.07", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.02.08", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.02.09", description: "Spare Parts" },
  { code: "16.02.10", description: "Maintenance during DLP" },
  { code: "16.03", description: "CRAH, CRAC & AHU" },
  { code: "16.03.01", description: "Equipment Supply – CRAC Units" },
  { code: "16.03.02", description: "Equipment Supply – CRAH Units" },
  { code: "16.03.03", description: "Equipment Supply – AHUs" },
  { code: "16.03.04", description: "Pre-Fabricated Skids" },
  { code: "16.03.05", description: "Delivery & Installation" },
  { code: "16.03.06", description: "Commissioning" },
  { code: "16.03.07", description: "Design, Shop Drawings & Project Management" },
  { code: "16.03.08", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.03.09", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.03.10", description: "Spare Parts" },
  { code: "16.03.11", description: "Maintenance during DLP" },
  { code: "16.04", description: "FWU & CDU" },
  { code: "16.04.01", description: "Equipment Supply – FWU" },
  { code: "16.04.02", description: "Equipment Supply – CDU" },
  { code: "16.04.03", description: "Equipment Supply – Associated Pumps / Controls (CDU package)" },
  { code: "16.04.04", description: "Pre-Fabricated Skids" },
  { code: "16.04.05", description: "Delivery & Installation" },
  { code: "16.04.06", description: "Commissioning" },
  { code: "16.04.07", description: "Design, Shop Drawings & Project Management" },
  { code: "16.04.08", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.04.09", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.04.10", description: "Spare Parts" },
  { code: "16.04.11", description: "Maintenance during DLP" },
  { code: "16.05", description: "UPS, PDU, PTU & Power Conditioning" },
  { code: "16.05.01", description: "Equipment Supply – UPS Modules" },
  { code: "16.05.02", description: "Equipment Supply – Battery Systems (VRLA, Li-ion, chargers)" },
  { code: "16.05.03", description: "Equipment Supply – Static / Maintenance Bypass Switchgear" },
  { code: "16.05.04", description: "Equipment Supply – PDUs" },
  { code: "16.05.05", description: "Equipment Supply – PTUs" },
  { code: "16.05.06", description: "Pre-Fabricated Skids" },
  { code: "16.05.07", description: "Delivery & Installation" },
  { code: "16.05.08", description: "Commissioning" },
  { code: "16.05.09", description: "Design, Shop Drawings & Project Management" },
  { code: "16.05.10", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.05.11", description: "Options / Vendor-Specific Inclusions" },
  { code: "16.05.12", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.05.13", description: "Spare Parts" },
  { code: "16.05.14", description: "Maintenance during DLP" },
  { code: "16.06", description: "Generators & Fuel Systems" },
  { code: "16.06.01", description: "Equipment Supply – Generators" },
  { code: "16.06.02", description: "Equipment Supply – Containerisation" },
  { code: "16.06.03", description: "Fuel Storage & Transfer Systems" },
  { code: "16.06.04", description: "Pre-Fabricated Skids" },
  { code: "16.06.05", description: "Delivery & Installation" },
  { code: "16.06.06", description: "Commissioning" },
  { code: "16.06.07", description: "Commissioning Fuel" },
  { code: "16.06.08", description: "First Fill Fuel" },
  { code: "16.06.09", description: "Design, Shop Drawings & Project Management" },
  { code: "16.06.10", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.06.11", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.06.12", description: "Spare Parts" },
  { code: "16.06.13", description: "Maintenance during DLP" },
  { code: "16.07", description: "Switchgear & Distribution" },
  { code: "16.07.01", description: "Equipment Supply – MV Switchboards / Kiosks" },
  { code: "16.07.02", description: "Equipment Supply – LV Switchboards" },
  { code: "16.07.03", description: "Pre-Fabricated Skids" },
  { code: "16.07.04", description: "Delivery & Installation" },
  { code: "16.07.05", description: "Commissioning" },
  { code: "16.07.06", description: "Design, Shop Drawings & Project Management" },
  { code: "16.07.07", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.07.08", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.07.09", description: "Spare Parts" },
  { code: "16.07.10", description: "Maintenance during DLP" },
  { code: "16.08", description: "Transformers" },
  { code: "16.08.01", description: "Equipment Supply – MV Transformers" },
  { code: "16.08.02", description: "Equipment Supply – Kiosk Transformers" },
  { code: "16.08.03", description: "Pre-Fabricated Skids" },
  { code: "16.08.04", description: "Delivery & Installation" },
  { code: "16.08.05", description: "Commissioning" },
  { code: "16.08.06", description: "Design, Shop Drawings & Project Management" },
  { code: "16.08.07", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.08.08", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.08.09", description: "Spare Parts" },
  { code: "16.08.10", description: "Maintenance during DLP" },
  { code: "16.09", description: "Busway / Busduct Systems" },
  { code: "16.09.01", description: "Equipment Supply – Busduct" },
  { code: "16.09.02", description: "Equipment Supply – Tap-Off Boxes (TOBs)" },
  { code: "16.09.03", description: "Equipment Supply – Feeder Boxes" },
  { code: "16.09.04", description: "Delivery & Installation" },
  { code: "16.09.05", description: "Commissioning" },
  { code: "16.09.06", description: "Design, Shop Drawings & Project Management" },
  { code: "16.09.07", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.09.08", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.09.09", description: "Spare Parts" },
  { code: "16.09.10", description: "Maintenance during DLP" },
  { code: "16.10", description: "Load Banks" },
  { code: "16.10.01", description: "Equipment Supply – Permanent Load Banks" },
  { code: "16.10.02", description: "Equipment Supply – Temporary / Rental Load Banks" },
  { code: "16.10.03", description: "Delivery & Installation" },
  { code: "16.10.04", description: "Commissioning" },
  { code: "16.10.05", description: "Design, Shop Drawings & Project Management" },
  { code: "16.10.06", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.10.07", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.10.08", description: "Spare Parts" },
  { code: "16.10.09", description: "Maintenance during DLP" },
  { code: "16.11", description: "Security Systems" },
  { code: "16.11.01", description: "Equipment Supply – Security Equipment" },
  { code: "16.11.02", description: "Delivery & Installation" },
  { code: "16.11.03", description: "Commissioning" },
  { code: "16.11.04", description: "Design, Shop Drawings & Project Management" },
  { code: "16.11.05", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.11.06", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.11.07", description: "Spare Parts" },
  { code: "16.11.08", description: "Maintenance during DLP" },
  { code: "16.12", description: "BMS & Controls Hardware" },
  { code: "16.12.01", description: "Equipment Supply – Controllers & Panels" },
  { code: "16.12.02", description: "Equipment Supply – Sensors & Field Devices (long lead items)" },
  { code: "16.12.03", description: "Delivery & Installation" },
  { code: "16.12.04", description: "Commissioning & Integration" },
  { code: "16.12.05", description: "Design, Shop Drawings & Project Management" },
  { code: "16.12.06", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.12.07", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.12.08", description: "Spare Parts" },
  { code: "16.12.09", description: "Maintenance during DLP" },
  { code: "16.13", description: "Substation Switchgear & Distribution" },
  { code: "16.13.01", description: "Equipment Supply – HV Switchboards / Kiosks" },
  { code: "16.13.02", description: "Equipment Supply – MV Switchboards" },
  { code: "16.13.03", description: "Pre-Fabricated Skids" },
  { code: "16.13.04", description: "Delivery & Installation" },
  { code: "16.13.05", description: "Commissioning" },
  { code: "16.13.06", description: "Design, Shop Drawings & Project Management" },
  { code: "16.13.07", description: "Defect Liability / Warranty (DLP)" },
  { code: "16.13.08", description: "Storage, Logistics, Transport & Insurance" },
  { code: "16.13.09", description: "Spare Parts" },
  { code: "16.13.10", description: "Maintenance during DLP" },
  { code: "17", description: "IT & AV" },
  { code: "17.01", description: "Structured Cabling & Fibre Backbone" },
  { code: "17.02", description: "IT Network Equipment – Switches, Routers, Racks" },
  { code: "17.03", description: "AV Systems – Screens, Audio, Conference Room Tech" },
  { code: "17.04", description: "Monitoring & Management Systems (NMS, DCIM, EMS)" },
  { code: "17.05", description: "Licenses & Subscriptions" },
  { code: "17.06", description: "Workstations, Laptops & Peripherals" },
  { code: "17.07", description: "Testing, Commissioning & Validation" },
  { code: "17.08", description: "Temporary IT / Construction Phase Connectivity" },
  { code: "17.09", description: "Spares" },
  { code: "18", description: "Construction" },
  { code: "18.01", description: "Supervision & Management" },
  { code: "18.01.01", description: "Supervision & Management" },
  { code: "18.01.02", description: "Site Set-Up" },
  { code: "18.01.03", description: "Site Management" },
  { code: "18.01.04", description: "GC Fee" },
  { code: "18.01.05", description: "GC Contingency" },
  { code: "18.02", description: "Land Development" },
  { code: "18.02.01", description: "Site Clearing & Vegetation Removal" },
  { code: "18.02.02", description: "Demolition" },
  { code: "18.02.03", description: "Bulk Earthworks" },
  { code: "18.02.04", description: "Ground Remediation" },
  { code: "18.03", description: "Site Infrastructure" },
  { code: "18.03.01", description: "Stormwater" },
  { code: "18.03.02", description: "Water" },
  { code: "18.03.03", description: "Sewer" },
  { code: "18.03.04", description: "Gas" },
  { code: "18.03.05", description: "Electrical" },
  { code: "18.03.06", description: "Telecommunications" },
  { code: "18.03.07", description: "Civil" },
  { code: "18.03.08", description: "Fencing" },
  { code: "18.03.09", description: "Security" },
  { code: "18.03.10", description: "External Lighting" },
  { code: "18.03.11", description: "Landscaping" },
  { code: "18.03.12", description: "Piling" },
  { code: "18.03.13", description: "Ground Improvements" },
  { code: "18.04", description: "Data Center Build (Cold Shell)" },
  { code: "18.04.01", description: "Foundations" },
  { code: "18.04.02", description: "Ground Slab" },
  { code: "18.04.03", description: "Retaining Walls / Basement Walls" },
  { code: "18.04.04", description: "Structural Steelwork" },
  { code: "18.04.05", description: "Precast Concrete Frame" },
  { code: "18.04.06", description: "In-Situ Concrete Frame" },
  { code: "18.04.07", description: "Suspended Concrete Slabs / Frames" },
  { code: "18.04.09", description: "External Walls & Cladding" },
  { code: "18.04.10", description: "Glazing Systems" },
  { code: "18.04.11", description: "Roofing & Waterproofing" },
  { code: "18.04.12", description: "Internal Walls" },
  { code: "18.04.13", description: "Internal, External Doors & Roller Shutters" },
  { code: "18.04.14", description: "Floor Finishes" },
  { code: "18.04.15", description: "Ceiling Finishes" },
  { code: "18.04.16", description: "Wall Finishes (paint, coverings)" },
  { code: "18.04.17", description: "Joinery & Hardware" },
  { code: "18.04.18", description: "Bathrooms & Amenities" },
  { code: "18.04.19", description: "Signage & Wayfinding" },
  { code: "18.04.20", description: "Passenger Lifts" },
  { code: "18.04.21", description: "Goods Hoists / Dock Levellers" },
  { code: "18.04.22", description: "Mechanical Services" },
  { code: "18.04.23", description: "Electrical Services" },
  { code: "18.04.24", description: "Fire Protection Systems" },
  { code: "18.04.25", description: "Hydraulic Services" },
  { code: "18.04.26", description: "Controls" },
  { code: "18.04.27", description: "Communications" },
  { code: "18.04.28", description: "Security Systems" },
  { code: "18.04.29", description: "Cranes & Heavy Lifting" },
  { code: "18.05", description: "Data Center Build (Warm Shell)" },
  { code: "18.05.01", description: "Foundations" },
  { code: "18.05.02", description: "Ground Slab" },
  { code: "18.05.03", description: "Retaining Walls / Basement Walls" },
  { code: "18.05.04", description: "Structural Steelwork" },
  { code: "18.05.05", description: "Precast Concrete Frame" },
  { code: "18.05.06", description: "In-Situ Concrete Frame" },
  { code: "18.05.07", description: "Suspended Concrete Slabs / Frames" },
  { code: "18.05.09", description: "External Walls & Cladding" },
  { code: "18.05.10", description: "Glazing Systems" },
  { code: "18.05.11", description: "Roofing & Waterproofing" },
  { code: "18.05.12", description: "Internal Walls" },
  { code: "18.05.13", description: "Internal, External Doors & Roller Shutters" },
  { code: "18.05.14", description: "Floor Finishes" },
  { code: "18.05.15", description: "Ceiling Finishes" },
  { code: "18.05.16", description: "Wall Finishes (paint, coverings)" },
  { code: "18.05.17", description: "Joinery & Hardware" },
  { code: "18.05.18", description: "Bathrooms & Amenities" },
  { code: "18.05.19", description: "Corporate Signage & Wayfinding" },
  { code: "18.05.20", description: "Passenger Lifts" },
  { code: "18.05.21", description: "Goods Hoists / Dock Levellers" },
  { code: "18.05.22", description: "Mechanical Services" },
  { code: "18.05.23", description: "Electrical Services" },
  { code: "18.05.24", description: "Fire Protection Systems" },
  { code: "18.05.25", description: "Hydraulic Services" },
  { code: "18.05.26", description: "Controls" },
  { code: "18.05.27", description: "Communications" },
  { code: "18.05.29", description: "Technical Cleaning" },
  { code: "18.05.30", description: "Cranes & Heavy Lifting" },
  { code: "18.06", description: "Tech Build (Office / Ancillary Buildings – Shell)" },
  { code: "18.06.01", description: "Foundations" },
  { code: "18.06.02", description: "Ground Slab" },
  { code: "18.06.03", description: "Retaining Walls / Basement Walls" },
  { code: "18.06.04", description: "Structural Steelwork" },
  { code: "18.06.05", description: "Precast Concrete Frame" },
  { code: "18.06.06", description: "In-Situ Concrete Frame" },
  { code: "18.06.07", description: "Suspended Concrete Slabs / Frames" },
  { code: "18.06.09", description: "External Walls & Cladding" },
  { code: "18.06.10", description: "Glazing Systems" },
  { code: "18.06.11", description: "Roofing & Waterproofing" },
  { code: "18.06.12", description: "Internal Walls" },
  { code: "18.06.13", description: "Internal, External Doors & Roller Shutters" },
  { code: "18.06.14", description: "Floor Finishes" },
  { code: "18.06.15", description: "Ceiling Finishes" },
  { code: "18.06.16", description: "Wall Finishes (paint, coverings)" },
  { code: "18.06.17", description: "Joinery & Hardware" },
  { code: "18.06.18", description: "Bathrooms & Amenities" },
  { code: "18.06.19", description: "Passenger Lifts" },
  { code: "18.06.20", description: "Goods Hoists / Dock Levellers" },
  { code: "18.06.21", description: "Mechanical Services" },
  { code: "18.06.22", description: "Electrical Services" },
  { code: "18.06.23", description: "Fire Protection Systems" },
  { code: "18.06.24", description: "Hydraulic Services" },
  { code: "18.06.25", description: "Controls" },
  { code: "18.06.26", description: "Communications" },
  { code: "18.06.28", description: "Cranes & Heavy Lifting" },
  { code: "18.06.29", description: "Corporate Signage & Wayfinding" },
  { code: "18.06.30", description: "Testing, Commissioning & Handover" },
  { code: "18.07", description: "Tech Fit-Out (Office Fit-Out)" },
  { code: "18.07.01", description: "Internal Walls" },
  { code: "18.07.02", description: "Floor Finishes" },
  { code: "18.07.03", description: "Ceiling Finishes" },
  { code: "18.07.04", description: "Wall Finishes (paint, coverings)" },
  { code: "18.07.05", description: "Joinery & Hardware" },
  { code: "18.07.06", description: "Mechanical Services" },
  { code: "18.07.07", description: "Electrical Services" },
  { code: "18.07.08", description: "Fire Protection Systems" },
  { code: "18.07.09", description: "Hydraulic Services" },
  { code: "18.07.10", description: "Communications" },
  { code: "18.07.11", description: "ICT / AV Systems" },
  { code: "18.07.12", description: "Security Systems" },
  { code: "18.07.13", description: "Bathrooms & Amenities" },
  { code: "18.07.14", description: "Office Amenities" },
  { code: "18.07.15", description: "Furniture, Fixtures & Equipment (FF&E)" },
  { code: "18.07.16", description: "Corporate Signage & Wayfinding" },
  { code: "19", description: "Customer" },
  { code: "19.01", description: "Customer Fit-Out 1" },
  { code: "19.01.01", description: "Supervision & Management" },
  { code: "19.01.01.01", description: "Supervision & Management" },
  { code: "19.01.01.02", description: "Site Set-Up" },
  { code: "19.01.01.03", description: "Site Management" },
  { code: "19.01.01.04", description: "GC Fee" },
  { code: "19.01.02", description: "Data Hall" },
  { code: "19.01.02.01", description: "Internal Walls" },
  { code: "19.01.02.02", description: "Floor Finishes" },
  { code: "19.01.02.03", description: "Ceiling Finishes" },
  { code: "19.01.02.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.01.02.05", description: "Internal Doors" },
  { code: "19.01.02.06", description: "Joinery & Hardware" },
  { code: "19.01.02.07", description: "Hot Ailse Containment" },
  { code: "19.01.02.08", description: "Mechanical Services" },
  { code: "19.01.02.09", description: "Electrical Services" },
  { code: "19.01.02.10", description: "Fire Protection Systems" },
  { code: "19.01.02.11", description: "Hydraulic Services" },
  { code: "19.01.02.12", description: "Controls" },
  { code: "19.01.02.13", description: "Communications" },
  { code: "19.01.02.14", description: "ICT / AV Systems" },
  { code: "19.01.02.15", description: "Security Systems" },
  { code: "19.01.02.16", description: "Technical Cleaning" },
  { code: "19.01.03", description: "Office & Stores" },
  { code: "19.01.03.01", description: "Internal Walls" },
  { code: "19.01.03.02", description: "Floor Finishes" },
  { code: "19.01.03.03", description: "Ceiling Finishes" },
  { code: "19.01.03.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.01.03.05", description: "Joinery & Hardware" },
  { code: "19.01.03.06", description: "Mechanical Services" },
  { code: "19.01.03.07", description: "Electrical Services" },
  { code: "19.01.03.08", description: "Fire Protection Systems" },
  { code: "19.01.03.09", description: "Hydraulic Services" },
  { code: "19.01.03.10", description: "Communications" },
  { code: "19.01.03.11", description: "ICT / AV Systems" },
  { code: "19.01.03.12", description: "Security Systems" },
  { code: "19.01.03.13", description: "Bathrooms & Amenities" },
  { code: "19.01.03.14", description: "Office Amenities" },
  { code: "19.01.03.15", description: "Furniture, Fixtures & Equipment (FF&E)" },
  { code: "19.01.03.16", description: "Corporate Signage & Wayfinding" },
  { code: "19.02", description: "Customer Fit-Out 2" },
  { code: "19.02.01", description: "Supervision & Management" },
  { code: "19.02.01.01", description: "Supervision & Management" },
  { code: "19.02.01.02", description: "Site Set-Up" },
  { code: "19.02.01.03", description: "Site Management" },
  { code: "19.02.01.04", description: "GC Fee" },
  { code: "19.02.02", description: "Data Hall" },
  { code: "19.02.02.01", description: "Internal Walls" },
  { code: "19.02.02.02", description: "Floor Finishes" },
  { code: "19.02.02.03", description: "Ceiling Finishes" },
  { code: "19.02.02.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.02.02.05", description: "Internal Doors" },
  { code: "19.02.02.06", description: "Joinery & Hardware" },
  { code: "19.02.02.07", description: "Hot Ailse Containment" },
  { code: "19.02.02.08", description: "Mechanical Services" },
  { code: "19.02.02.09", description: "Electrical Services" },
  { code: "19.02.02.10", description: "Fire Protection Systems" },
  { code: "19.02.02.11", description: "Hydraulic Services" },
  { code: "19.02.02.12", description: "Controls" },
  { code: "19.02.02.13", description: "Communications" },
  { code: "19.02.02.14", description: "ICT / AV Systems" },
  { code: "19.02.02.15", description: "Security Systems" },
  { code: "19.02.02.16", description: "Technical Cleaning" },
  { code: "19.02.03", description: "Office & Stores" },
  { code: "19.02.03.01", description: "Internal Walls" },
  { code: "19.02.03.02", description: "Floor Finishes" },
  { code: "19.02.03.03", description: "Ceiling Finishes" },
  { code: "19.02.03.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.02.03.05", description: "Joinery & Hardware" },
  { code: "19.02.03.06", description: "Mechanical Services" },
  { code: "19.02.03.07", description: "Electrical Services" },
  { code: "19.02.03.08", description: "Fire Protection Systems" },
  { code: "19.02.03.09", description: "Hydraulic Services" },
  { code: "19.02.03.10", description: "Communications" },
  { code: "19.02.03.11", description: "ICT / AV Systems" },
  { code: "19.02.03.12", description: "Security Systems" },
  { code: "19.02.03.13", description: "Bathrooms & Amenities" },
  { code: "19.02.03.14", description: "Office Amenities" },
  { code: "19.02.03.15", description: "Furniture, Fixtures & Equipment (FF&E)" },
  { code: "19.02.03.16", description: "Corporate Signage & Wayfinding" },
  { code: "19.03", description: "Customer Fit-Out 3" },
  { code: "19.03.01", description: "Supervision & Management" },
  { code: "19.03.01.01", description: "Supervision & Management" },
  { code: "19.03.01.02", description: "Site Set-Up" },
  { code: "19.03.01.03", description: "Site Management" },
  { code: "19.03.01.04", description: "GC Fee" },
  { code: "19.03.02", description: "Data Hall" },
  { code: "19.03.02.01", description: "Internal Walls" },
  { code: "19.03.02.02", description: "Floor Finishes" },
  { code: "19.03.02.03", description: "Ceiling Finishes" },
  { code: "19.03.02.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.03.02.05", description: "Internal Doors" },
  { code: "19.03.02.06", description: "Joinery & Hardware" },
  { code: "19.03.02.07", description: "Hot Ailse Containment" },
  { code: "19.03.02.08", description: "Mechanical Services" },
  { code: "19.03.02.09", description: "Electrical Services" },
  { code: "19.03.02.10", description: "Fire Protection Systems" },
  { code: "19.03.02.11", description: "Hydraulic Services" },
  { code: "19.03.02.12", description: "Controls" },
  { code: "19.03.02.13", description: "Communications" },
  { code: "19.03.02.14", description: "ICT / AV Systems" },
  { code: "19.03.02.15", description: "Security Systems" },
  { code: "19.03.02.16", description: "Technical Cleaning" },
  { code: "19.03.03", description: "Office & Stores" },
  { code: "19.03.03.01", description: "Internal Walls" },
  { code: "19.03.03.02", description: "Floor Finishes" },
  { code: "19.03.03.03", description: "Ceiling Finishes" },
  { code: "19.03.03.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.03.03.05", description: "Joinery & Hardware" },
  { code: "19.03.03.06", description: "Mechanical Services" },
  { code: "19.03.03.07", description: "Electrical Services" },
  { code: "19.03.03.08", description: "Fire Protection Systems" },
  { code: "19.03.03.09", description: "Hydraulic Services" },
  { code: "19.03.03.10", description: "Communications" },
  { code: "19.03.03.11", description: "ICT / AV Systems" },
  { code: "19.03.03.12", description: "Security Systems" },
  { code: "19.03.03.13", description: "Bathrooms & Amenities" },
  { code: "19.03.03.14", description: "Office Amenities" },
  { code: "19.03.03.15", description: "Furniture, Fixtures & Equipment (FF&E)" },
  { code: "19.03.03.16", description: "Corporate Signage & Wayfinding" },
  { code: "19.04", description: "Customer Fit-Out 4" },
  { code: "19.04.01", description: "Supervision & Management" },
  { code: "19.04.01.01", description: "Supervision & Management" },
  { code: "19.04.01.02", description: "Site Set-Up" },
  { code: "19.04.01.03", description: "Site Management" },
  { code: "19.04.01.04", description: "GC Fee" },
  { code: "19.04.02", description: "Data Hall" },
  { code: "19.04.02.01", description: "Internal Walls" },
  { code: "19.04.02.02", description: "Floor Finishes" },
  { code: "19.04.02.03", description: "Ceiling Finishes" },
  { code: "19.04.02.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.04.02.05", description: "Internal Doors" },
  { code: "19.04.02.06", description: "Joinery & Hardware" },
  { code: "19.04.02.07", description: "Hot Ailse Containment" },
  { code: "19.04.02.08", description: "Mechanical Services" },
  { code: "19.04.02.09", description: "Electrical Services" },
  { code: "19.04.02.10", description: "Fire Protection Systems" },
  { code: "19.04.02.11", description: "Hydraulic Services" },
  { code: "19.04.02.12", description: "Controls" },
  { code: "19.04.02.13", description: "Communications" },
  { code: "19.04.02.14", description: "ICT / AV Systems" },
  { code: "19.04.02.15", description: "Security Systems" },
  { code: "19.04.02.16", description: "Technical Cleaning" },
  { code: "19.04.03", description: "Office & Stores" },
  { code: "19.04.03.01", description: "Internal Walls" },
  { code: "19.04.03.02", description: "Floor Finishes" },
  { code: "19.04.03.03", description: "Ceiling Finishes" },
  { code: "19.04.03.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.04.03.05", description: "Joinery & Hardware" },
  { code: "19.04.03.06", description: "Mechanical Services" },
  { code: "19.04.03.07", description: "Electrical Services" },
  { code: "19.04.03.08", description: "Fire Protection Systems" },
  { code: "19.04.03.09", description: "Hydraulic Services" },
  { code: "19.04.03.10", description: "Communications" },
  { code: "19.04.03.11", description: "ICT / AV Systems" },
  { code: "19.04.03.12", description: "Security Systems" },
  { code: "19.04.03.13", description: "Bathrooms & Amenities" },
  { code: "19.04.03.14", description: "Office Amenities" },
  { code: "19.04.03.15", description: "Furniture, Fixtures & Equipment (FF&E)" },
  { code: "19.04.03.16", description: "Corporate Signage & Wayfinding" },
  { code: "19.05", description: "Customer Fit-Out 5" },
  { code: "19.05.01", description: "Supervision & Management" },
  { code: "19.05.01.01", description: "Supervision & Management" },
  { code: "19.05.01.02", description: "Site Set-Up" },
  { code: "19.05.01.03", description: "Site Management" },
  { code: "19.05.01.04", description: "GC Fee" },
  { code: "19.05.02", description: "Data Hall" },
  { code: "19.05.02.01", description: "Internal Walls" },
  { code: "19.05.02.02", description: "Floor Finishes" },
  { code: "19.05.02.03", description: "Ceiling Finishes" },
  { code: "19.05.02.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.05.02.05", description: "Internal Doors" },
  { code: "19.05.02.06", description: "Joinery & Hardware" },
  { code: "19.05.02.07", description: "Hot Ailse Containment" },
  { code: "19.05.02.08", description: "Mechanical Services" },
  { code: "19.05.02.09", description: "Electrical Services" },
  { code: "19.05.02.10", description: "Fire Protection Systems" },
  { code: "19.05.02.11", description: "Hydraulic Services" },
  { code: "19.05.02.12", description: "Controls" },
  { code: "19.05.02.13", description: "Communications" },
  { code: "19.05.02.14", description: "ICT / AV Systems" },
  { code: "19.05.02.15", description: "Security Systems" },
  { code: "19.05.02.16", description: "Technical Cleaning" },
  { code: "19.05.03", description: "Office & Stores" },
  { code: "19.05.03.01", description: "Internal Walls" },
  { code: "19.05.03.02", description: "Floor Finishes" },
  { code: "19.05.03.03", description: "Ceiling Finishes" },
  { code: "19.05.03.04", description: "Wall Finishes (paint, coverings)" },
  { code: "19.05.03.05", description: "Joinery & Hardware" },
  { code: "19.05.03.06", description: "Mechanical Services" },
  { code: "19.05.03.07", description: "Electrical Services" },
  { code: "19.05.03.08", description: "Fire Protection Systems" },
  { code: "19.05.03.09", description: "Hydraulic Services" },
  { code: "19.05.03.10", description: "Communications" },
  { code: "19.05.03.11", description: "ICT / AV Systems" },
  { code: "19.05.03.12", description: "Security Systems" },
  { code: "19.05.03.13", description: "Bathrooms & Amenities" },
  { code: "19.05.03.14", description: "Office Amenities" },
  { code: "19.05.03.15", description: "Furniture, Fixtures & Equipment (FF&E)" },
  { code: "19.05.03.16", description: "Corporate Signage & Wayfinding" },
  { code: "49", description: "Contingency" },
  { code: "49.01", description: "Development Contingency" },
  { code: "50", description: "GSDC Internal Operations Costs" },
  { code: "51", description: "Operations" },
  { code: "99", description: "Contingency" },
  { code: "99.01", description: "Operations Contingency" },
] as const;

export type ApprovedCostWbsTemplateEntry = (typeof APPROVED_COST_WBS_TEMPLATE)[number];

/** Parent code for hierarchy (e.g. `11.01.01` → `11.01`; top-level codes return null). */
export function parentCodeForApprovedWbs(code: string): string | null {
  const dotIndex = code.lastIndexOf(".");
  if (dotIndex === -1) return null;
  return code.slice(0, dotIndex);
}
